### ISSUE TITLE
Cool!! :-)

### ISSUE THREAD

**Issue by michael-brade** [tamuratak/latex-utensils#21]
Hi, 
this is awesome to see! With your project you basically solved my issue: https://github.com/michael-brade/LaTeX.js/issues/10 :grin: 

Great work! I hope you don't mind if I steal some of your ideas for the LaTeX.js AST :)

cheers, Michael

**Comment by tamuratak** [comment]
Thank you too for `LaTeX.js`. It is honor to help the development of `LaTeX.js`. 

Notice that `latex-utensils` accepts invalid LaTeX documents. For example, it does not throw any error parsing the following document:

```
\begin{document}  % no \end{document}
```

This is because we want to parse documents users are editing as possible as. Validation should be implemented separately if it is needed.

White space handling is also not strict. See #16. This is due to my lack of understanding LaTeX.

**Comment by michael-brade** [comment]
Yeah, good point! With a pure parser, invalid documents can be handled - not so in `LaTeX.js`...

Also, I try to be absolutely correct with whitespace. I have one challenge left regarding it and I want to fix it (if possible) before switching to an AST. We'll see :-)

If it is only a lack of understanding LaTeX, you can take a look at my whitespace unit tests. They should be pretty complete.
